# Generated by Django 2.2.3 on 2019-07-10 23:28

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190710_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.get_image_path),
        ),
    ]
