# Generated by Django 2.2.2 on 2019-08-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190718_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_in_stock',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
