# Generated by Django 2.2.2 on 2019-08-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_num_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
